export type currentUserProps = {
  _id: string,
  name: string,
  email: string,
  hashedPassword: string,
  isAgent: boolean,
  profileImage: { public_id: string, secure_url: string},
  image: string,
  mobileNumber: string,
  officeNumber: string,
  city: string,
  state: string,
  agencyName: string,
  agencyAddress: string,
  agencyFee: number,
  agentBio: string,
  occupation: string,
  isVerified: boolean,
  numberOfClient: number,
  numberOfBlogs: number,
  numberOfSoldProperties: number,
  numberOfPropertiesManaged: number,
  agencyWebsite: string,
  clients: string[],
  blogs: string[],
  profileCreated: boolean,
  properties: string[],
  createdAt: string,
  updatedAt: string,
  ratings: number,
}